credentials:
  usernames:
    user1:
      email: user1@example.com
      name: User One
      id: "uuid-user1"  # Замените на реальный user_id из Supabase
      password: "$2b$12$eIXOuJrUQEe/EZ/ClJZQJ.H4aW0TbZIWv5M4i6Q8IICkD6bVjRmG6"  # Хэш пароля "password1"
    user2:
      email: user2@example.com
      name: User Two
      id: "uuid-user2"  # Замените на реальный user_id из Supabase
      password: "$2b$12$eIXOuJrUQEe/EZ/ClJZQJ.H4aW0TbZIWv5M4i6Q8IICkD6bVjRmG6"  # Хэш пароля "password2"
cookie:
  expiry_days: 30
  key: your_random_signature_key  # Замените на случайную строку
  name: your_cookie_name
preauthorized: []
