# secrets.toml
SUPABASE_URL = "https://hrdwrclycbelsmvlarnp.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyZHdyY2x5Y2JlbHNtdmxhcm5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzMTEwOTYsImV4cCI6MjA1Mzg4NzA5Nn0.FOa7rjQ3TNpLoWpJtWlvShjbHyPcrDcd0YV_QoTOiDE"
